//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHFFamily
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AHFFamily()
        {
            this.AHFDisease = new HashSet<AHFDisease>();
        }
    
        public int Id { get; set; }
        public int AHFId { get; set; }
        public Nullable<bool> Grandfather { get; set; }
        public Nullable<bool> Grandmother { get; set; }
        public Nullable<bool> Father { get; set; }
        public Nullable<bool> Mother { get; set; }
        public Nullable<bool> Brothers { get; set; }
        public Nullable<bool> Uncles { get; set; }
    
        public virtual AHF AHF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AHFDisease> AHFDisease { get; set; }
    }
}
