//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequestDeliveredTransaction
    {
        public int Id { get; set; }
        public int AlmBranchRequestDeliveredId { get; set; }
        public int AlmBranchRequestToDeliveryTransactionId { get; set; }
        public int ConceptId { get; set; }
        public decimal Sended { get; set; }
        public decimal Price { get; set; }
        public decimal MinPrice { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmBranchRequestDelivered AlmBranchRequestDelivered { get; set; }
        public virtual AlmBranchRequestToDeliveryTransaction AlmBranchRequestToDeliveryTransaction { get; set; }
        public virtual Concept Concept { get; set; }
    }
}
