//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequestToDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchRequestToDelivery()
        {
            this.AlmBranchBilling = new HashSet<AlmBranchBilling>();
            this.AlmBranchRequestDelivered = new HashSet<AlmBranchRequestDelivered>();
            this.AlmBranchRequestToDeliveryTransaction = new HashSet<AlmBranchRequestToDeliveryTransaction>();
            this.IReturn = new HashSet<IReturn>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmBranchRequestConfirmedId { get; set; }
        public int AlmStatusId { get; set; }
        public bool Seen { get; set; }
        public string Comments { get; set; }
        public bool Delivered { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchBilling> AlmBranchBilling { get; set; }
        public virtual AlmBranchRequestConfirmed AlmBranchRequestConfirmed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestDelivered> AlmBranchRequestDelivered { get; set; }
        public virtual AlmStatus AlmStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestToDeliveryTransaction> AlmBranchRequestToDeliveryTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IReturn> IReturn { get; set; }
    }
}
