//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequestConfirmedTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchRequestConfirmedTransaction()
        {
            this.AlmBranchRequestToDeliveryTransaction = new HashSet<AlmBranchRequestToDeliveryTransaction>();
        }
    
        public int Id { get; set; }
        public int AlmBranchRequestConfirmedId { get; set; }
        public int AlmBranchRequestResponseTransactionId { get; set; }
        public int ConceptId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public bool ToDelivery { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmBranchRequestConfirmed AlmBranchRequestConfirmed { get; set; }
        public virtual AlmBranchRequestResponseTransaction AlmBranchRequestResponseTransaction { get; set; }
        public virtual Concept Concept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestToDeliveryTransaction> AlmBranchRequestToDeliveryTransaction { get; set; }
    }
}
