//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequestResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchRequestResponse()
        {
            this.AlmBranchRequestConfirmed = new HashSet<AlmBranchRequestConfirmed>();
            this.AlmBranchRequestRejected = new HashSet<AlmBranchRequestRejected>();
            this.AlmBranchRequestResponseTransaction = new HashSet<AlmBranchRequestResponseTransaction>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmBranchRequestId { get; set; }
        public int AlmStatusId { get; set; }
        public bool Seen { get; set; }
        public string WarehouseComments { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmBranchRequest AlmBranchRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestConfirmed> AlmBranchRequestConfirmed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestRejected> AlmBranchRequestRejected { get; set; }
        public virtual AlmStatus AlmStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestResponseTransaction> AlmBranchRequestResponseTransaction { get; set; }
    }
}
