//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequestToDeliveryTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchRequestToDeliveryTransaction()
        {
            this.AlmBranchRequestDeliveredTransaction = new HashSet<AlmBranchRequestDeliveredTransaction>();
            this.IReturnProducts = new HashSet<IReturnProducts>();
        }
    
        public int Id { get; set; }
        public int AlmBranchRequestToDeliveryId { get; set; }
        public int AlmBranchRequestConfirmedId { get; set; }
        public int AlmBranchRequestConfirmedTransactionId { get; set; }
        public int ConceptId { get; set; }
        public decimal ToSend { get; set; }
        public bool Delivered { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<int> AlmStockId { get; set; }
    
        public virtual AlmBranchRequestConfirmedTransaction AlmBranchRequestConfirmedTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestDeliveredTransaction> AlmBranchRequestDeliveredTransaction { get; set; }
        public virtual AlmBranchRequestToDelivery AlmBranchRequestToDelivery { get; set; }
        public virtual AlmStock AlmStock { get; set; }
        public virtual Concept Concept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IReturnProducts> IReturnProducts { get; set; }
    }
}
