//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchRequest()
        {
            this.AlmBranchRequestResponse = new HashSet<AlmBranchRequestResponse>();
            this.AlmBranchRequestTransaction = new HashSet<AlmBranchRequestTransaction>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int ClinicId { get; set; }
        public int AlmStatusId { get; set; }
        public bool Seen { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmStatus AlmStatus { get; set; }
        public virtual Clinic Clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestResponse> AlmBranchRequestResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchRequestTransaction> AlmBranchRequestTransaction { get; set; }
    }
}
