//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmBranchBilling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmBranchBilling()
        {
            this.AlmBranchBillingPayment = new HashSet<AlmBranchBillingPayment>();
            this.AlmBranchBillingTransaction = new HashSet<AlmBranchBillingTransaction>();
        }
    
        public int id { get; set; }
        public decimal Total { get; set; }
        public bool Closed { get; set; }
        public bool Paid { get; set; }
        public int AlmBranchRequestToDeliveryId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual AlmBranchRequestToDelivery AlmBranchRequestToDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchBillingPayment> AlmBranchBillingPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmBranchBillingTransaction> AlmBranchBillingTransaction { get; set; }
    }
}
