//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmFolio
    {
        public int Id { get; set; }
        public int BranchRequestFolio { get; set; }
        public int BranchRequestResponseFolio { get; set; }
        public int BranchRequestConfirmedFolio { get; set; }
        public int BranchRequestRejectedFolio { get; set; }
        public int BranchRequestToDeliveryFolio { get; set; }
        public int BranchRequestDeliveredFolio { get; set; }
    }
}
