//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmInvoice()
        {
            this.AlmInvoiceTransaction = new HashSet<AlmInvoiceTransaction>();
            this.AlmRecordInvoice = new HashSet<AlmRecordInvoice>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<int> SupplierRequestDeliveredId { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AlmSupplier AlmSupplier { get; set; }
        public virtual AlmSupplierRequestDelivered AlmSupplierRequestDelivered { get; set; }
        public virtual AlmUser AlmUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmInvoiceTransaction> AlmInvoiceTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmRecordInvoice> AlmRecordInvoice { get; set; }
    }
}
