//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmRecordInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmRecordInvoice()
        {
            this.AlmRecordTransactionInvoice = new HashSet<AlmRecordTransactionInvoice>();
        }
    
        public int RecordInvoiceId { get; set; }
        public int InvoiceId { get; set; }
        public string Code { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public int Version { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual AlmInvoice AlmInvoice { get; set; }
        public virtual AlmSupplier AlmSupplier { get; set; }
        public virtual AlmUser AlmUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmRecordTransactionInvoice> AlmRecordTransactionInvoice { get; set; }
    }
}
