//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestResponseTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestResponseTransaction()
        {
            this.AlmSupplierRequestConfirmedTransaction = new HashSet<AlmSupplierRequestConfirmedTransaction>();
        }
    
        public int Id { get; set; }
        public int AlmSupplierRequestResponseId { get; set; }
        public int AlmSupplierRequestTransactionId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public int ConceptId { get; set; }
        public Nullable<decimal> Requested { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmSupplier AlmSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestConfirmedTransaction> AlmSupplierRequestConfirmedTransaction { get; set; }
        public virtual AlmSupplierRequestResponse AlmSupplierRequestResponse { get; set; }
        public virtual AlmSupplierRequestTransaction AlmSupplierRequestTransaction { get; set; }
        public virtual Concept Concept { get; set; }
    }
}
