//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestToDeliveryTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestToDeliveryTransaction()
        {
            this.AlmReturnProducts = new HashSet<AlmReturnProducts>();
            this.AlmSupplierRequestDeliveredTransaction = new HashSet<AlmSupplierRequestDeliveredTransaction>();
        }
    
        public int Id { get; set; }
        public int AlmSupplierRequestToDeliveryId { get; set; }
        public int AlmSupplierRequestConfirmedId { get; set; }
        public int AlmSupplierRequestConfirmedTransactionId { get; set; }
        public int ConceptId { get; set; }
        public decimal ToSend { get; set; }
        public bool Delivered { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public decimal MaxPrice { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmReturnProducts> AlmReturnProducts { get; set; }
        public virtual AlmSupplierRequestConfirmedTransaction AlmSupplierRequestConfirmedTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestDeliveredTransaction> AlmSupplierRequestDeliveredTransaction { get; set; }
        public virtual AlmSupplierRequestToDelivery AlmSupplierRequestToDelivery { get; set; }
        public virtual Concept Concept { get; set; }
    }
}
