//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestConfirmedTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestConfirmedTransaction()
        {
            this.AlmSupplierRequestToDeliveryTransaction = new HashSet<AlmSupplierRequestToDeliveryTransaction>();
        }
    
        public int Id { get; set; }
        public int AlmSupplierRequestConfirmedId { get; set; }
        public int AlmSupplierRequestResponseTransactionId { get; set; }
        public int ConceptId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public bool ToDelivery { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmSupplierRequestConfirmed AlmSupplierRequestConfirmed { get; set; }
        public virtual AlmSupplierRequestResponseTransaction AlmSupplierRequestResponseTransaction { get; set; }
        public virtual Concept Concept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestToDeliveryTransaction> AlmSupplierRequestToDeliveryTransaction { get; set; }
    }
}
