//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierFolio
    {
        public int Id { get; set; }
        public int SupplierRequestFolio { get; set; }
        public int SupplierRequestResponseFolio { get; set; }
        public int SupplierRequestConfirmedFolio { get; set; }
        public int SupplierRequestRejectedFolio { get; set; }
        public int SupplierRequestToDeliveryFolio { get; set; }
        public int SupplierRequestDeliveredFolio { get; set; }
        public int SupplierRequestCancelled { get; set; }
    }
}
