//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestResponse()
        {
            this.AlmSupplierRequestConfirmed = new HashSet<AlmSupplierRequestConfirmed>();
            this.AlmSupplierRequestRejected = new HashSet<AlmSupplierRequestRejected>();
            this.AlmSupplierRequestResponseTransaction = new HashSet<AlmSupplierRequestResponseTransaction>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmSupplierId { get; set; }
        public int AlmSupplierRequestId { get; set; }
        public int AlmStatusId { get; set; }
        public bool Seen { get; set; }
        public string WarehouseComments { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmStatus AlmStatus { get; set; }
        public virtual AlmSupplier AlmSupplier { get; set; }
        public virtual AlmSupplierRequest AlmSupplierRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestConfirmed> AlmSupplierRequestConfirmed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestRejected> AlmSupplierRequestRejected { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestResponseTransaction> AlmSupplierRequestResponseTransaction { get; set; }
    }
}
