//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestRejected
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestRejected()
        {
            this.AlmSupplierRequestRejectedTransaction = new HashSet<AlmSupplierRequestRejectedTransaction>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmSupplierRequestResponseId { get; set; }
        public int AlmStatusId { get; set; }
        public int AlmSupplierId { get; set; }
        public string Comments { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmStatus AlmStatus { get; set; }
        public virtual AlmSupplier AlmSupplier { get; set; }
        public virtual AlmSupplierRequestResponse AlmSupplierRequestResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestRejectedTransaction> AlmSupplierRequestRejectedTransaction { get; set; }
    }
}
