//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmSupplierRequestToDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlmSupplierRequestToDelivery()
        {
            this.AlmReturn = new HashSet<AlmReturn>();
            this.AlmSupplierBilling = new HashSet<AlmSupplierBilling>();
            this.AlmSupplierRequestDelivered = new HashSet<AlmSupplierRequestDelivered>();
            this.AlmSupplierRequestToDeliveryTransaction = new HashSet<AlmSupplierRequestToDeliveryTransaction>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmSupplierRequestConfirmedId { get; set; }
        public int AlmStatusId { get; set; }
        public int AlmSupplierId { get; set; }
        public bool Seen { get; set; }
        public string Comments { get; set; }
        public bool Delivered { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmReturn> AlmReturn { get; set; }
        public virtual AlmStatus AlmStatus { get; set; }
        public virtual AlmSupplier AlmSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierBilling> AlmSupplierBilling { get; set; }
        public virtual AlmSupplierRequestConfirmed AlmSupplierRequestConfirmed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestDelivered> AlmSupplierRequestDelivered { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmSupplierRequestToDeliveryTransaction> AlmSupplierRequestToDeliveryTransaction { get; set; }
    }
}
