//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Disease { get; set; }
        public string CurrentDisease { get; set; }
        public Nullable<bool> Surgical { get; set; }
        public string Surgical_string { get; set; }
        public Nullable<bool> Transfuctional { get; set; }
        public string Transfunctional_string { get; set; }
        public Nullable<bool> Trauma { get; set; }
        public string Trauma_string { get; set; }
        public Nullable<bool> PreviousInternals { get; set; }
        public string PreviousInternals_string { get; set; }
        public Nullable<bool> Allergic { get; set; }
        public string Allergic_string { get; set; }
        public string Tobacco_question { get; set; }
        public string Tobacco_string { get; set; }
        public string Alcohol_question { get; set; }
        public string Alcohol_string { get; set; }
        public string Drugs_question { get; set; }
        public string Drugs_string { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
