//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledPackages
    {
        public int Id { get; set; }
        public Nullable<int> OrderPackageId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> NewOrder { get; set; }
        public Nullable<int> OldOrder { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<decimal> Refund { get; set; }
    
        public virtual OrderPackage OrderPackage { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
