//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIE10
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIE10()
        {
            this.CourseThreatment = new HashSet<CourseThreatment>();
            this.Diagnostic = new HashSet<Diagnostic>();
            this.EvolCourseThreatment = new HashSet<EvolCourseThreatment>();
            this.EvolDiagnostic = new HashSet<EvolDiagnostic>();
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int Consecutivo { get; set; }
        public string Letra { get; set; }
        public string Catalog_Key { get; set; }
        public Nullable<bool> Asterisco { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> LSex { get; set; }
        public string LInf { get; set; }
        public string LSup { get; set; }
        public Nullable<bool> Trivial { get; set; }
        public Nullable<bool> Erradicado { get; set; }
        public Nullable<bool> N_Inter { get; set; }
        public Nullable<bool> NIN { get; set; }
        public Nullable<bool> NINMTOBS { get; set; }
        public Nullable<bool> NO_CBD { get; set; }
        public Nullable<bool> NO_APH { get; set; }
        public Nullable<bool> FETAL { get; set; }
        public Nullable<int> DIA_CAPITULO_TYPE { get; set; }
        public string DESCRIPCION_CAPITULO { get; set; }
        public string RUBRICA_TYPE { get; set; }
        public string YEAR_MODIFI { get; set; }
        public string YEAR_APLICACION { get; set; }
        public Nullable<bool> NOTDIARIA { get; set; }
        public Nullable<bool> NOTSEMANAL { get; set; }
        public Nullable<bool> SISTEMA_ESPECIAL { get; set; }
        public Nullable<bool> BIRMM { get; set; }
        public Nullable<int> CVE_CAUSA_TYPE { get; set; }
        public string CAUSA_TYPE { get; set; }
        public Nullable<bool> EPI_MORTA { get; set; }
        public Nullable<bool> EPI_MORTA_M5 { get; set; }
        public Nullable<bool> EDAS_E_IRAS_EN_M5 { get; set; }
        public string LISTA1 { get; set; }
        public string LISTA5 { get; set; }
        public string PRINMORTA { get; set; }
        public string PRINMORBI { get; set; }
        public string LM_MORBI { get; set; }
        public string LM_MORTA { get; set; }
        public Nullable<int> LGBD165 { get; set; }
        public Nullable<int> LOMSBECK { get; set; }
        public Nullable<int> LGBD190 { get; set; }
        public Nullable<bool> ES_CAUSES { get; set; }
        public string NUM_CAUSES { get; set; }
        public Nullable<bool> ES_SUIVE_MORTA { get; set; }
        public string DAGA { get; set; }
        public string EPI_CLAVE { get; set; }
        public string EPI_CLAVE_DESC { get; set; }
        public Nullable<bool> ES_SUIVE_MORB { get; set; }
        public Nullable<bool> ES_SUIVE_NOTIN { get; set; }
        public Nullable<bool> ES_SUIVE_EST_EPI { get; set; }
        public Nullable<bool> ES_SUIVE_EST_BROTE { get; set; }
        public Nullable<bool> SINAC { get; set; }
        public Nullable<bool> CODIGOX { get; set; }
        public Nullable<bool> COD_SIT_LESION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseThreatment> CourseThreatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostic> Diagnostic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolCourseThreatment> EvolCourseThreatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolDiagnostic> EvolDiagnostic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
