//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostInBranch
    {
        public int Id { get; set; }
        public int ConceptId { get; set; }
        public int ClinicId { get; set; }
        public int AlmStockId { get; set; }
        public decimal Cost { get; set; }
        public decimal MinPrice { get; set; }
        public decimal BasePrice { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual AlmStock AlmStock { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Concept Concept { get; set; }
    }
}
