//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denomination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Denomination()
        {
            this.DenominationByCashClose = new HashSet<DenominationByCashClose>();
            this.DenominationWithdrawal = new HashSet<DenominationWithdrawal>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public string MoneyCode { get; set; }
        public bool Active { get; set; }
        public int PaymentTypeId { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenominationByCashClose> DenominationByCashClose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenominationWithdrawal> DenominationWithdrawal { get; set; }
    }
}
