//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceAndSystems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceAndSystems()
        {
            this.ElectronicFile = new HashSet<ElectronicFile>();
        }
    
        public int Id { get; set; }
        public string Respiratory { get; set; }
        public string Cardiovascular { get; set; }
        public string Digestive { get; set; }
        public string Urinary { get; set; }
        public string Musculoskeletal { get; set; }
        public string Genital { get; set; }
        public string Hematological { get; set; }
        public string Endocrine { get; set; }
        public string Nervous { get; set; }
        public string Psychosomatic { get; set; }
        public string Others { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicFile> ElectronicFile { get; set; }
    }
}
