//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectronicFile()
        {
            this.Diagnostic = new HashSet<Diagnostic>();
            this.ElectronicFileUpdate = new HashSet<ElectronicFileUpdate>();
            this.EvolutionNote = new HashSet<EvolutionNote>();
            this.Exam = new HashSet<Exam>();
            this.InterconsultNote = new HashSet<InterconsultNote>();
            this.PreviousResult = new HashSet<PreviousResult>();
            this.ProductNote = new HashSet<ProductNote>();
            this.ReferenceNote = new HashSet<ReferenceNote>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<int> DeviceAndSystemsId { get; set; }
        public Nullable<int> CurrentConditionId { get; set; }
        public Nullable<int> ExplorationId { get; set; }
        public Nullable<int> MedicId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual CurrentCondition CurrentCondition { get; set; }
        public virtual DeviceAndSystems DeviceAndSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostic> Diagnostic { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Exploration Exploration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicFileUpdate> ElectronicFileUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolutionNote> EvolutionNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterconsultNote> InterconsultNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreviousResult> PreviousResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNote> ProductNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceNote> ReferenceNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
