//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolutionNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvolutionNote()
        {
            this.EvFile = new HashSet<EvFile>();
            this.EvolDiagnostic = new HashSet<EvolDiagnostic>();
            this.EvolPreviousResult = new HashSet<EvolPreviousResult>();
            this.Product = new HashSet<Product>();
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ElectronicFileId { get; set; }
        public Nullable<int> EvolCurrentConditionId { get; set; }
        public Nullable<int> EvolExplorationId { get; set; }
        public Nullable<int> EvolDiagnosticId { get; set; }
        public Nullable<int> EvolCommentsId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> ConceptId { get; set; }
    
        public virtual Concept Concept { get; set; }
        public virtual ElectronicFile ElectronicFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvFile> EvFile { get; set; }
        public virtual EvolComments EvolComments { get; set; }
        public virtual EvolCurrentCondition EvolCurrentCondition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolDiagnostic> EvolDiagnostic { get; set; }
        public virtual EvolDiagnostic EvolDiagnostic1 { get; set; }
        public virtual EvolExploration EvolExploration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolPreviousResult> EvolPreviousResult { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
