//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolCourseThreatment
    {
        public int Id { get; set; }
        public Nullable<int> EvolCurrentConditionId { get; set; }
        public Nullable<int> CIE10Id { get; set; }
        public string Medicine { get; set; }
        public string Dose { get; set; }
        public string GeneralIndication { get; set; }
    
        public virtual CIE10 CIE10 { get; set; }
        public virtual EvolCurrentCondition EvolCurrentCondition { get; set; }
    }
}
