//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolDiagnostic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvolDiagnostic()
        {
            this.EvolutionNote1 = new HashSet<EvolutionNote>();
        }
    
        public int id { get; set; }
        public Nullable<int> EvolutionNoteId { get; set; }
        public Nullable<int> CIE10Id { get; set; }
        public string Pronostic { get; set; }
        public Nullable<int> Dose { get; set; }
        public string Presentation { get; set; }
        public string WayOfAdministration { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> DaysOfThreatment { get; set; }
        public string ActiveSubstance { get; set; }
        public string CommercialBrand { get; set; }
        public string Unit { get; set; }
        public string DiagnosticName { get; set; }
        public string RecipeText { get; set; }
    
        public virtual CIE10 CIE10 { get; set; }
        public virtual EvolutionNote EvolutionNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolutionNote> EvolutionNote1 { get; set; }
    }
}
