//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.FormData = new HashSet<FormData>();
            this.Laboratory = new HashSet<Laboratory>();
            this.Xray = new HashSet<Xray>();
        }
    
        public int id { get; set; }
        public int ElectronicFileId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public int MedicId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ConceptId { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Age { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual ElectronicFile ElectronicFile { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormData> FormData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laboratory> Laboratory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xray> Xray { get; set; }
    }
}
