//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int id { get; set; }
        public int CashClosingId { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Created { get; set; }
        public int idUser { get; set; }
    
        public virtual CashClosing CashClosing { get; set; }
        public virtual User User { get; set; }
    }
}
