//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMovement
    {
        public int id { get; set; }
        public int ConceptId { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public bool Iva { get; set; }
        public decimal Price { get; set; }
        public int InvoiceId { get; set; }
        public int CurrentIva { get; set; }
        public Nullable<int> DeliveredTransactionId { get; set; }
        public Nullable<int> StockId { get; set; }
    
        public virtual Concept Concept { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
