//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IReturn()
        {
            this.IReturnProducts = new HashSet<IReturnProducts>();
        }
    
        public int Id { get; set; }
        public string Reason { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int UpdatedId { get; set; }
        public Nullable<int> AlmBranchRequestToDeliveryId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual AlmBranchRequestToDelivery AlmBranchRequestToDelivery { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IReturnProducts> IReturnProducts { get; set; }
    }
}
