//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IReturnProducts
    {
        public int Id { get; set; }
        public string Reason { get; set; }
        public int Quantity { get; set; }
        public int ConceptId { get; set; }
        public int IReturnId { get; set; }
        public System.DateTime Created { get; set; }
        public int AlmStockId { get; set; }
        public Nullable<int> AlmBranchRequestToDeliveryTransactionId { get; set; }
        public Nullable<int> Returned { get; set; }
        public Nullable<int> StockId { get; set; }
    
        public virtual AlmBranchRequestToDeliveryTransaction AlmBranchRequestToDeliveryTransaction { get; set; }
        public virtual AlmStock AlmStock { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual IReturn IReturn { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
