//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int Id { get; set; }
        public string TypeOfInput { get; set; }
        public string InOrOutOfBox { get; set; }
        public Nullable<int> TherapeuticGroupNumber { get; set; }
        public string TherapeuticGroupName { get; set; }
        public string LevelOfAttention { get; set; }
        public string Code { get; set; }
        public string SubCode { get; set; }
        public string GenericName { get; set; }
        public string PharmaceuticalForm { get; set; }
        public string Concentration { get; set; }
        public string Presentation { get; set; }
        public string MainIndication { get; set; }
        public string OtherIndications { get; set; }
        public string TypeOfUpdate { get; set; }
        public string UpdateNumber { get; set; }
        public string CompleteDescription { get; set; }
    }
}
