//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurserySummary
    {
        public int id { get; set; }
        public int InternmentId { get; set; }
        public System.DateTime Date { get; set; }
        public string Value { get; set; }
        public int NurseryMeasurementId { get; set; }
    
        public virtual Internment Internment { get; set; }
        public virtual NurseryMeasurements NurseryMeasurements { get; set; }
    }
}
