//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPackage()
        {
            this.CancelledPackages = new HashSet<CancelledPackages>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int PackageId { get; set; }
        public int MedicId { get; set; }
        public int ClinicId { get; set; }
        public Nullable<System.DateTime> Scheduled { get; set; }
        public string Medicname { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledPackages> CancelledPackages { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Package Package { get; set; }
    }
}
