//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public int OrderId { get; set; }
        public int EmployeeId { get; set; }
        public int PaymentTypeId { get; set; }
        public decimal Amount { get; set; }
        public decimal Commission { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public string NumOperation { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
