//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousResult
    {
        public int Id { get; set; }
        public Nullable<int> ElectronicFileId { get; set; }
        public Nullable<int> Cholesterol { get; set; }
        public Nullable<System.DateTime> DateOfTaking_Cholesterol { get; set; }
        public Nullable<int> Triglycerides { get; set; }
        public Nullable<System.DateTime> DateOfTaking_Triglycerides { get; set; }
        public Nullable<int> Glucose { get; set; }
        public Nullable<System.DateTime> DateOfTaking_Glucose { get; set; }
        public string Glucose_Category { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ElectronicFile ElectronicFile { get; set; }
        public virtual User User { get; set; }
    }
}
