//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceNote
    {
        public int Id { get; set; }
        public Nullable<int> ElectronicFileId { get; set; }
        public Nullable<int> EstablishmentThatSends { get; set; }
        public string EstablishmentThatReceives { get; set; }
        public string DiagnosticCriteria { get; set; }
        public string StudyPlan { get; set; }
        public string Suggestions { get; set; }
        public string CounterReference { get; set; }
        public string ShippingReason { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ElectronicFile ElectronicFile { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
