//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelFormField
    {
        public int id { get; set; }
        public int FormId { get; set; }
        public int FieldId { get; set; }
        public int Position { get; set; }
        public bool Required { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Form Form { get; set; }
    }
}
