//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabletCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabletCart()
        {
            this.tabletCartConcepts = new HashSet<tabletCartConcepts>();
        }
    
        public int id { get; set; }
        public int EmployeeId { get; set; }
        public int PatientId { get; set; }
        public int ClinicId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabletCartConcepts> tabletCartConcepts { get; set; }
    }
}
