//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAllProductsExist
    {
        public Nullable<int> Id { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Code { get; set; }
        public int ConceptId { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public bool Deleted { get; set; }
        public bool Iva { get; set; }
        public int InStock { get; set; }
        public string Batch { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<int> stockId { get; set; }
    }
}
