//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAlmBranchRequestToDeliveryTransaction
    {
        public int AlmBranchRequestToDeliveryTransactionId { get; set; }
        public int AlmBranchRequestConfirmedId { get; set; }
        public int AlmBranchRequestConfirmedTransactionId { get; set; }
        public int AlmBranchRequestToDeliveryId { get; set; }
        public int Id { get; set; }
        public int ConceptId { get; set; }
        public string Concept { get; set; }
        public string Code { get; set; }
        public decimal Price { get; set; }
        public decimal ToSend { get; set; }
        public bool Iva { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> AlmStockId { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Batch { get; set; }
        public decimal MaxPrice { get; set; }
    }
}
