//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAlmSupplierRequestSupplier
    {
        public int Id { get; set; }
        public int Folio { get; set; }
        public Nullable<int> responseSupplierId { get; set; }
        public bool RequestStatus { get; set; }
        public string Status { get; set; }
        public int AlmStatusId { get; set; }
        public System.DateTime Created { get; set; }
        public bool Seen { get; set; }
        public Nullable<int> hasResponse { get; set; }
        public Nullable<int> supplierProductId { get; set; }
        public string Name { get; set; }
    }
}
