//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAlmUserTimeHandler
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int RoleId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Updated { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public Nullable<bool> Islogin { get; set; }
        public Nullable<int> DifferenceTime { get; set; }
    }
}
