//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAlmSupplierReqResult
    {
        public int Id { get; set; }
        public int Folio { get; set; }
        public int AlmStatusId { get; set; }
        public bool Seen { get; set; }
        public System.DateTime requestCreated { get; set; }
        public System.DateTime requestUpdated { get; set; }
        public Nullable<System.DateTime> deliveredCreated { get; set; }
        public Nullable<System.DateTime> deliveredUpdated { get; set; }
        public int ConceptId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Sended { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    }
}
