//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCancelledTickets
    {
        public int id { get; set; }
        public decimal Total { get; set; }
        public string Created { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string sDateCancelled { get; set; }
        public Nullable<int> Ticket { get; set; }
        public int ClinicId { get; set; }
    }
}
