//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCashClosing
    {
        public Nullable<int> Number { get; set; }
        public int id { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> Efective { get; set; }
        public Nullable<decimal> CreditCard { get; set; }
        public Nullable<decimal> Vales { get; set; }
        public Nullable<decimal> TotalFisic { get; set; }
        public Nullable<decimal> TotalSale { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SoldItems { get; set; }
        public int ClinicId { get; set; }
    }
}
