//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwConsultByPatient
    {
        public int OrderId { get; set; }
        public string Ticket { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Created { get; set; }
        public int ConsultId { get; set; }
        public int PatientId { get; set; }
        public int StatusId { get; set; }
        public string FullName { get; set; }
    }
}
