//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDiscountClinic
    {
        public int id { get; set; }
        public string DiscountName { get; set; }
        public string DiscountDescription { get; set; }
        public string DiscountTypeDescription { get; set; }
        public string ClinicName { get; set; }
        public string Percentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public bool Deleted { get; set; }
    }
}
