//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDonations
    {
        public int orderId { get; set; }
        public Nullable<int> Ticket { get; set; }
        public int PatientId { get; set; }
        public int EmployeeId { get; set; }
        public string patientName { get; set; }
        public string employeeName { get; set; }
        public int ClinicId { get; set; }
        public string clinicName { get; set; }
        public decimal Donation { get; set; }
        public System.DateTime Created { get; set; }
    }
}
