//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatientChronicDisease
    {
        public string PatientName { get; set; }
        public string PatientLastName { get; set; }
        public System.DateTime PatientBirthDate { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public string PatientSex { get; set; }
        public string CountyName { get; set; }
        public string PatientPhoneNumber { get; set; }
        public string ChronicDiseaseCode { get; set; }
        public Nullable<int> ClinicId { get; set; }
    }
}
