//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPharmacyProductivity
    {
        public int Id { get; set; }
        public int ConceptId { get; set; }
        public int CategoryId { get; set; }
        public int EmployeeId { get; set; }
        public string ConceptName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public decimal Profit { get; set; }
        public string CategoryName { get; set; }
        public string RoleName { get; set; }
        public string MedicName { get; set; }
        public int Quantity { get; set; }
        public int ClinicId { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public int OrderId { get; set; }
        public string TextPromotion { get; set; }
        public Nullable<int> discounttypeId { get; set; }
        public string DiscountTypeDescription { get; set; }
        public Nullable<int> DiscountId { get; set; }
    }
}
