//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRoundings
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime Created { get; set; }
        public int OrderId { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Rounding { get; set; }
        public int ClinicId { get; set; }
        public Nullable<int> Ticket { get; set; }
    }
}
