//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSales
    {
        public int OrderId { get; set; }
        public int OrderTicket { get; set; }
        public string Ticket { get; set; }
        public int ClinicId { get; set; }
        public string ClinicName { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeFullName { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFullName { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal Discount { get; set; }
        public bool Paid { get; set; }
        public bool IsCanceled { get; set; }
        public string sCreated { get; set; }
        public System.DateTime PaymentCreated { get; set; }
    }
}
