//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchedule
    {
        public int id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<int> MedicId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ConceptId { get; set; }
        public Nullable<System.DateTime> Scheduled { get; set; }
        public string sScheduled { get; set; }
        public string PatientName { get; set; }
        public Nullable<System.DateTime> PatientBirthDate { get; set; }
        public string sPatientBirthDate { get; set; }
        public string ClinicName { get; set; }
        public string MedicName { get; set; }
        public string StatusName { get; set; }
        public string ConceptName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> OrderCreated { get; set; }
        public string sOrderCreated { get; set; }
    }
}
