//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserTimeHandler
    {
        public int id { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> UserActive { get; set; }
        public bool Authenticator { get; set; }
        public int UpdatedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDemo { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public Nullable<int> CurrentClinicId { get; set; }
        public Nullable<int> DifferenceTime { get; set; }
    }
}
