//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMEDIK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseSuply
    {
        public int id { get; set; }
        public int StockId { get; set; }
        public int ConceptId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int Employeid { get; set; }
        public int ClinicId { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
